/// <reference types="vite-plugin-svgr/client" />
export { default as NotiIcon } from "@/assets/svg/notif.svg?react";
export { default as ChevronRightIcon } from "@/assets/svg/chevron-right.svg?react";
export { default as TierIcon } from "@/assets/svg/tier.svg?react";
export { default as PointsIcon } from "@/assets/svg/points.svg?react";
export { default as VoucherIcon } from "@/assets/svg/voucher.svg?react";
export { default as RewardIcon } from "@/assets/svg/reward.svg?react";
export { default as ChallengeIcon } from "@/assets/svg/challenge.svg?react";
export { default as CopyIcon } from "@/assets/svg/copy.svg?react";
export { default as InfoIcon } from "@/assets/svg/info.svg?react";
export { default as FilterIcon } from "@/assets/svg/filter.svg?react";
export { default as CrownIcon } from "@/assets/svg/crown.svg?react";
export { default as NotificationIcon } from "@/assets/svg/icons_notification.svg?react";
export { default as MissionIcon } from "@/assets/svg/icons8-goal-20 1.svg?react";
export { default as CoinIcon } from "@/assets/svg/icons8-coin-40 1.svg?react";
export { default as GameIcon } from "@/assets/svg/icons8-goal-20 2 (1).svg?react";
export { default as HomeIcon } from "@/assets/svg/icons_home_2.svg?react";
export { default as ProfileIcon } from "@/assets/svg/icons_frame.svg?react";
export { default as ReceiptSearchIcon } from "@/assets/svg/icons_receipt_search.svg?react";
export { default as TicketIcon } from "@/assets/svg/icons_ticket.svg?react";
export { default as UnionIcon } from "@/assets/svg/Union.svg?react";
export { default as DrawerIcon } from "@/assets/svg/Group 6.svg?react";
export { default as ArrowLeftIcon } from "@/assets/svg/arrow-left.svg?react";
export { default as EditPenIcon } from "@/assets/svg/edit-2.svg?react";
export { default as LogoutIcon } from "@/assets/svg/logout.svg?react";
export { default as ReceiptDiscountIcon } from "@/assets/svg/receipt-disscount.svg?react";
export { default as MessageIcon } from "@/assets/svg/message.svg?react";
export { default as MessageQuestionIcon } from "@/assets/svg/message-question.svg?react";
export { default as ArchiveBookIcon } from "@/assets/svg/archive-book.svg?react";
export { default as Profile2UserIcon } from "@/assets/svg/profile-2user.svg?react";
export { default as Ticket2Icon } from "@/assets/svg/ticket-3.svg?react";
export { default as ArrowDownIcon } from "@/assets/svg/arrow-down.svg?react";
export { default as InfoEmptyIcons } from "@/assets/svg/info-empty.svg?react";
export { default as CalenderIcon } from "@/assets/svg/calendaricons_calendar.svg?react";
export { default as SearchIcon } from "@/assets/svg/search-normal.svg?react";
export { default as TicketIcon2 } from "@/assets/svg//icons_ticket_2.svg?react";
